### ISSUE TITLE
Implement Support for Auto Splitters

### ISSUE THREAD

**Issue by CryZe** [CryZe/livesplit-one-desktop#11]
There is a work in progress branch over here: https://github.com/CryZe/livesplit-one-desktop/tree/auto-splitting

**Comment by ThreeFx** [comment]
i'd be interested in testing autosplitting helping with the implementation (within my capabilities). As I currently understand we are testing WASM implementations? Are there any resources on this?

Side note: ATM the auto-splitting branch doesn't build since it expects a modified local version of `livesplit-core` which I couldn't find on GitHub.

**Comment by Shinmera** [comment]
Yeah, I can't seem to build that branch either. The cargo lock refers to a git hash that longer exists.
