### ISSUE TITLE
Splits and Layouts NOT A ISSUE

### ISSUE THREAD

**Issue by Lifecurse** [CryZe/livesplit-one-desktop#25]
not a issue but how would i customize it or use splits thanks :)

**Comment by CryZe** [comment]
For now the v0.0.1 that I just released is a very minimal version that doesn't offer any splits or layout editor. I locally have a version that has those, but it's not ready yet (I'm very unhappy with some parts). So instead in the v0.0.1 you configure it via a YAML file. 

Take a look here: 
https://github.com/CryZe/livesplit-one-desktop/blob/master/config.yaml

Copy that next to the executable and make changes. In YAML everything past the `#` in a line is a comment, so make sure to remove that to configure the splits / layout path / etc. 

Since there's no splits or layout editor yet, I'd recommend using the web version for those in the meantime: https://one.livesplit.org

**Comment by Lifecurse** [comment]
Thanks! i would use the web version but i need global hotkeys :(

**Comment by CryZe** [comment]
You only need the web version to create and modify the splits and layouts. You can export them from there and then use this version, which does have global hotkeys. Alternatively you can also just download some splits from https://splits.io

**Comment by Lifecurse** [comment]
i will thx :)

**Comment by whitewolfos** [comment]
Are there any instructions on how to configure the global hotkeys? I can load the splits in fine, but when I try to even un-comment the lines in the example yaml file:

```
hotkeys:
  # split: null
  undo_all_pauses: NumPad7
  toggle_timing_method: NumPad9
```

Then the splits don't load, which I assume means there is something bad with that hotkeys block. I need to be able to change the hotkeys because my computer doesn't have a NumPad, so I can't use any defaults. I really don't need anything fancy, just setting the buttons for `start / split` and `reset` would be enough. 

Thanks for the help!

**Comment by CryZe** [comment]
Seems like it's `Numpad` rather than `NumPad` by now.

https://github.com/LiveSplit/livesplit-core/blob/master/crates/livesplit-hotkey/src/linux/key_code.rs

**Comment by whitewolfos** [comment]
Oh, case matters, I see. 

My issue was I was trying to set a hotkey to the `r` key, but you have to set it to `R` to make it work. Just a silly mistake on my end, then.

Thanks for the speedy response!
